# Generated by Django 5.1.6 on 2025-03-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OCRImage',
        ),
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='uploaded_at',
            new_name='created_at',
        ),
    ]
