# Generated by Django 5.1.6 on 2025-04-25 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0003_alter_uploadedimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStruk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_toko', models.CharField(max_length=255)),
                ('tanggal', models.CharField(max_length=100)),
                ('subtotal', models.CharField(max_length=50, null=True)),
                ('pajak', models.CharField(max_length=50, null=True)),
                ('biaya_layanan', models.CharField(max_length=50, null=True)),
                ('diskon', models.CharField(max_length=50, null=True)),
                ('lainnya', models.CharField(max_length=50, null=True)),
                ('grand_total', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='Struk/'),
        ),
        migrations.CreateModel(
            name='DataProduk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('jumlah', models.CharField(max_length=50)),
                ('harga', models.CharField(max_length=50)),
                ('jumlah_harga', models.CharField(max_length=50)),
                ('struk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produk', to='ocr_app.datastruk')),
            ],
        ),
    ]
