# Generated by Django 5.1.6 on 2025-06-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0004_datastruk_alter_uploadedimage_image_dataproduk'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBensin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_SPBU', models.CharField(max_length=255)),
                ('tanggal', models.CharField(max_length=100)),
                ('total_bayar', models.CharField(max_length=50, null=True)),
                ('harga_per_liter', models.CharField(max_length=50, null=True)),
                ('jumlah_liter', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
